services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
    command: >
      sh -c "
        tail -f /dev/null
      "
    working_dir: /app
